###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  
  - id: "{{composer.name}}"
    name: Mautic theme with tokens
    type: theme
    subtype: mautic
    version: "1.0.0"
    description: "✨📬 Mautic Theme (with custom tokens) by PIGEONPOSSE"
    homepage: "https://packagist.org/packages/{{composer.name}}"
    logo: "https://raw.githubusercontent.com/pigeonposse/mautic-plugin-extra-tools/main/Assets/img/logo.png"
    repo: "https://github.com/{{composer.name}}"

###############################################################################
